# Basic
title: Forever
subtitle: Living tired is because the heart is filled with superfluous things,  restless overeating  silly to support has the same reason.
welcome_message: <a href="https://blog.csdn.net/ForeverBana" target="_blank">CSDN Blogs</a>
description: Live in the present.
creator: <a href="https://github.com/ForeverWx">@Forever</a>

url: "https://github.com/ForeverWx"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/ForeverWx'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: https://weibo.com/u/6461030147
    github: https://github.com/ForeverWx
    twitter: Forever
    gplus: 107108267983477358170
    mail: qq2244141460@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
